### PR TITLE
Support for Capacitor v6

### LINKED ISSUE #6: Capacitor 6.x compatibility
Any plans to migrate to Capacitor v6 ?

### PR DESCRIPTION
**Pull request by kreare**
Add support for Capacitor v6

### CODE REVIEW

**Comment by kduma** [comment]
Thank you for your contribution. I will check it before weekend.

**Comment by kduma** [comment]
Hi,

At least two things:

- Build files should not be included in repository, so please revert the [671e0c2](https://github.com/kduma-autoid/capacitor-sunmi-printer/pull/7/commits/671e0c255024e0b2937ac7942efb450b14a3292a) commit
- [Demo app](https://github.com/kduma-autoid/capacitor-sunmi-printer/tree/main/example) have to be also updated to capacitor V6

**Comment by kreare** [comment]
Updated the example to v6 but i'm unable to build the app (i was unable to build even with your original code). I don't know why. probably there is something wrong in my PC but my app, using your library builds fine...

**Comment by martinbertinat** [comment]
Hi @kreare. Thanks for your work getting capacitor v6.

We are trying to print but nothing happens.

Do you have a working example?

Thanks

**Comment by kreare** [comment]
hi.
not anymore as i've moved back to Cordova

**Comment by kduma** [comment]
Hi @kreare,

I have finalised the migration and merged your changes. Thanks for your contribution!

**Comment by kreare** [comment]
you are welcome and thank you for the merge

**Comment by kduma** [comment]
Hi @martinbertinat,

There is available an [example app with the source available](https://github.com/kduma-autoid/capacitor-sunmi-printer/tree/main/example), where you can test all the available methods from the SDK. If you don't want to compile ti by yourself, it is available to download from Sunmi App Store.

Just keep in mind that the first thing, you need to press the _bind_ button for the rest of methods to work.

**Pull request merged**
